CaseReviewApp/Models/Case.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CaseReviewApp.Models
{
    public class Case
    {
        [Key]
        public int CaseID { get; set; }
        [DisplayName("Case Title")]
        public String CaseTitle { get; set; }
        [DisplayName("Short Description")]
        public String ShortDescription { get; set; }
        [DisplayName("Created By")]
        public String CreatedBy { get; set; }
        [Column(TypeName = "datetime2")]
        [DisplayName("Created On")]
        public DateTime CreatedOn { get; set; }
    }
}

CaseReviewApp/Models/Member.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CaseReviewApp.Models
{
    public class Member
    {
        public int MemberID { get; set; }
        public String Name { get; set; }
        public String Email { get; set; }
        public virtual ICollection<ReviewPanel> ReviewPanels { get; set; }
    }
}

CaseReviewApp/Models/ReviewPanel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CaseReviewApp.Models
{
    public class ReviewPanel
    {
        [Key]
        public int ReviewID { get; set; }
        [DisplayName("Review Details")]
        public String ReviewDetails { get; set; }
        [DisplayName("Created By")]
        public String CreatedBy { get; set; }
        [Column(TypeName = "datetime2")]
        [DisplayName("Created On")]
        public DateTime CreatedOn { get; set; }
        public virtual ICollection<Member> Members { get; set; }
        public int CaseID { get; set; }
        public virtual Case Case { get; set; }
    }
}

CaseReviewApp/Models/ViewModels/PanelFormData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CaseReviewApp.Models.ViewModels
{
    public class PanelFormData
    {
        public int ReviewID { get; set; }
        public CaseMember[] Reviews { get; set; }
        public String ReviewDetails { get; set; }
        public String CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
    }

    public class CaseMember
    {
        public int CaseID { get; set; }
        public int[] Members { get; set; }
    }
}

CaseReviewApp/Models/ViewModels/ReviewPanelViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace CaseReviewApp.Models.ViewModels
{
    public class ReviewPanelViewModel
    {
        public int ReviewID { get; set; }
        [DisplayName("Case Title")]
        public String CaseTitle { get; set; }
        [DisplayName("Review Details")]
        public String ReviewDetails { get; set; }
        [DisplayName("Created By")]
        public String CreatedBy { get; set; }
        [DisplayName("Created On")]
        public DateTime CreatedOn { get; set; }
        [DisplayName("Panel Members")]
        public List<Member> Members { get; set; }
    }
}

CaseReviewApp/Controllers/CaseController.cs
using CaseReviewApp.DAL;
using CaseReviewApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaseReviewApp.Controllers
{
    public class CaseController : Controller
    {
        CaseReviewRepository repo = new CaseReviewRepository();
        // GET: Case
        public ActionResult Index()
        {
            List<Case> cases = new List<Case>();
            try
            {
                cases = repo.GetCases();
            }
            catch (Exception)
            {
                throw new Exception("Can not get cases");
            }
            
            return View(cases);
        }
        [HttpPost]
        public ActionResult Insert(Case @case)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    repo.InsertCase(@case);
                }
            }
            catch (Exception)
            {
                throw new Exception("Failed to insert new case");
            }
            
            return PartialView("_CaseDetails", repo.GetCases().ToList());
        }
    }
}

CaseReviewApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CaseReviewApp.DAL;

namespace CaseReviewApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

CaseReviewApp/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CaseReviewApp.DAL;
using CaseReviewApp.Models;

namespace CaseReviewApp.Controllers
{
    public class MemberController : Controller
    {
        CaseReviewRepository repo = new CaseReviewRepository();
        // GET: Member
        public ActionResult Index()
        {
            List<Member> members = new List<Member>();
            try
            {
                members = repo.GetMembers().ToList();
            }
            catch (Exception ex)
            {

                throw ex;
            }
            
            return View(members);
        }

        [HttpPost]
        public ActionResult Insert(Member member)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    repo.InsertMember(member);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return PartialView("_MemberDetails", repo.GetMembers().ToList());
        }
    }
}

CaseReviewApp/Controllers/ReviewPanelController.cs
using CaseReviewApp.DAL;
using CaseReviewApp.Models;
using CaseReviewApp.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaseReviewApp.Controllers
{
    public class ReviewPanelController : Controller
    {
        CaseReviewRepository repo = new CaseReviewRepository();
        // GET: ReviewPanel
        public ActionResult Index()
        {
            ViewBag.Cases = repo.AvailableCasesForReview();
            ViewBag.Members = repo.GetMembers().ToList();
            return View(repo.GetReviewPanels().ToList());
        }

        [HttpPost]
        public ActionResult Insert(PanelFormData panelData)
        {
            repo.InsertReviewPanel(panelData);
            var redirectUrl = new UrlHelper(Request.RequestContext).Action("Index", "ReviewPanel");
            return Json(new { Url = redirectUrl });
        }

        [HttpPost]
        public ActionResult Delete(int ReviewID)
        {
            repo.DeleteReview(ReviewID);
            var redirectUrl = new UrlHelper(Request.RequestContext).Action("Index", "ReviewPanel");
            return Json(new { Url = redirectUrl });
        }

        public ActionResult EditModalData(int ReviewID)
        {
            ReviewPanel reviewPanel = repo.GetReviewPanel(ReviewID);
            ViewBag.AllMembers = repo.GetMembers().ToList();
            return PartialView("_EditModalBody", reviewPanel);
        }

        public ActionResult UpdateReviewPanel(PanelFormData panelFormData)
        {
            repo.UpdateReviewPanel(panelFormData);
            var redirectUrl = new UrlHelper(Request.RequestContext).Action("Index", "ReviewPanel");
            return Json(new { Url = redirectUrl });
        }

    }
}

CaseReviewApp/Views/Case/Index.cshtml
@model IEnumerable<CaseReviewApp.Models.Case>

@{
    ViewBag.Title = "Cases";
}

<h2>Cases</h2>
<div class="row">
    <div class="col-md-6">
        <div id="case-table">
            @Html.Partial("_CaseDetails", Model)
        </div>

        <br />
        <a href="javascript::return false;" class="btn btn-primary" data-toggle="modal" data-target="#case-modal">Add New</a>

        <div class="modal fade" id="case-modal" data-keyboard="false" data-backdrop="static">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <a href="#" class="close" data-dismiss="modal">&times;</a>
                        <h2 class="modal-title">Create New Case</h2>
                    </div>
                    <div class="modal-body">
                        <form id="case-form">
                            <div class="form-group">
                                <label for="CaseTitle">Case Title</label>
                                <input type="text" required class="form-control" name="CaseTitle" placeholder="Write a title">
                            </div>
                            <div class="form-group">
                                <label for="ShortDescription">Case Description</label>
                                <input type="text" required class="form-control" name="ShortDescription" placeholder="Give a short Description" />
                            </div>
                            <div class="form-group">
                                <label for="CreatedBy">Created By</label>
                                <input type="text" required class="form-control" name="CreatedBy" placeholder="Name of the case creator">
                            </div>
                            <div class="form-group">
                                <label for="CreatedOn">Created On</label>
                                <input type="text" class="form-control" name="CreatedOn" placeholder="Creation time" value="@DateTime.Now">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript::return false;" id="btnCaseSubmit" class="btn btn-success pull-left">Submit</a>
                        <a href="#" data-dismiss="modal" class="btn btn-primary pull-left">Exit</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CaseReviewApp/Views/Case/_CaseDetails.cshtml
@model IEnumerable<CaseReviewApp.Models.Case>
@if (!Model.Any())
{
    <h3 class="text-warning">No cases added yet</h3>
}
else
{
    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CaseTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShortDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CaseTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ShortDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedOn)
                </td>

            </tr>
        }
    </table>
}

CaseReviewApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Case Review Panel";
}

<div class="row">
    <h2>Welcome to Case Review Panel Application</h2>

    <h4>What you can do?</h4>
    <div>
        <p>- Create Panel Members</p>
        <p>- Create Cases</p>
        <p>- Create Case Review Panels</p>
    </div>

</div>

CaseReviewApp/Views/Member/Index.cshtml
@model IEnumerable<CaseReviewApp.Models.Member>

@{
    ViewBag.Title = "Panel Members";
}

<h2>Panel Members</h2>

<div class="row">
    <div class="col-md-6">
        <div id="member-table">
            @Html.Partial("_MemberDetails", Model)
        </div>

        <br />
        <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#member-modal">Add New</a>

        <div class="modal fade" id="member-modal" data-keyboard="false" data-backdrop="static">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <a href="#" class="close" data-dismiss="modal">&times;</a>
                        <h2 class="modal-title">Create Panel Member</h2>
                    </div>
                    <div class="modal-body">
                        <form id="member-form">
                            <div class="form-group">
                                <label for="Name">Name</label>
                                <input type="text" class="form-control" name="Name" placeholder="Name" required>
                            </div>
                            <div class="form-group">
                                <label for="Email">Email</label>
                                <input type="email" class="form-control" name="Email" placeholder="Email" required>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript::return false;" id="btnMemberSubmit" class="btn btn-success pull-left">Save</a>
                        <a href="#" data-dismiss="modal" class="btn btn-primary pull-left">Exit</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CaseReviewApp/Views/Member/_MemberDetails.cshtml
@model IEnumerable<CaseReviewApp.Models.Member>
@if (!Model.Any())
{
    <h3 class="text-warning">No panel member available</h3>
}
else
{
    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
            </tr>
        }
    </table>
}
    

CaseReviewApp/Views/ReviewPanel/Index.cshtml
@model IEnumerable<CaseReviewApp.Models.ViewModels.ReviewPanelViewModel>
@{
    ViewBag.Title = "Review Panels";
}

<h2>Review Panels</h2>
<div class="row">
    <div class="col-md-8">
        <div id="review-table">
            @Html.Partial("_ReviewDetails", Model)
        </div>
        <input type="hidden" id="hiddenReviewId" />
        <br />
        <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#panel-modal">Add New</a>

        <div class="modal fade" id="panel-modal" data-keyboard="false" data-backdrop="static">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <a href="#" class="close" data-dismiss="modal">&times;</a>
                        <h2 class="modal-title">Create Case Review</h2>
                    </div>
                    <div class="modal-body">
                        @if (ViewBag.Cases.Count == 0)
                        {
                            <h4>No assignable cases available</h4>
                        }
                        else
                        {
                            <form id="panel-form">
                                <div class="row">
                                    <div class="col-md-6">
                                        <h4>Case Title</h4>
                                    </div>
                                    <div class="col-md-6">
                                        <h4>Panel Members</h4>
                                    </div>
                                </div>
                                @foreach (var caseItem in ViewBag.Cases)
                                {
                                    <input type="hidden" class="hiddenCaseId" value="@caseItem.CaseID" />
                                    <div class="row" id="check_@caseItem.CaseID">
                                        <div class="col-md-6">
                                            <div class="checkbox">
                                                <label><input type="checkbox" id="case_@caseItem.CaseID" />@caseItem.CaseTitle</label>
                                            </div>
                                        </div>
                                        <div class="col-md-6 member">
                                            @foreach (var member in ViewBag.Members)
                                            {
                                                <div class="checkbox">
                                                    <label><input type="checkbox" id="@(String.Format("case_{0}_{1}", caseItem.CaseID, member.MemberID))" />@member.Name</label>
                                                </div>
                                            }
                                        </div>
                                    </div>
                                    <hr />
                                }
                                <span class="case-list-msg error"></span>

                                <div class="form-group">
                                    <label for="ReviewDetails">Review Details</label>
                                    <input type="text" required class="form-control" name="ReviewDetails" placeholder="Some details about the review">
                                </div>
                                <div class="form-group">
                                    <label for="CreatedBy">Created By</label>
                                    <input type="text" required class="form-control" name="CreatedBy" placeholder="Name of the creator">
                                </div>
                                <div class="form-group">
                                    <label for="CreatedOn">Created On</label>
                                    <input type="text" required class="form-control" name="CreatedOn" value="@DateTime.Now" placeholder="Creation time">
                                </div>
                            </form>
                        }

                    </div>
                    <div class="modal-footer">
                        @if (ViewBag.Cases.Count > 0)
                        {
                            <a href="#" id="btnPanelSubmit" class="btn btn-success pull-left">Save</a>
                        }
                        <a href="#" data-dismiss="modal" class="btn btn-primary pull-left">Exit</a>
                    </div>
                </div>
            </div>
        </div>

        @*Delete Modal*@
        <div class="modal fade" id="del-modal" data-keyboard="false" data-backdrop="static">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <a href="#" class="close" data-dismiss="modal">&times;</a>
                        <h3 class="modal-title">Delete case review</h3>
                    </div>
                    <div class="modal-body">
                        <h4>Are you sure?</h4>
                    </div>
                    <div class="modal-footer">
                        <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
                        <a href="javascript::return false;" class="btn btn-success" onclick="DeleteReview()">Confirm</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="panel-modal-edit" data-keyboard="false" data-backdrop="static">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <a href="#" class="close" data-dismiss="modal">&times;</a>
                        <h2 class="modal-title">Update Case Review</h2>
                    </div>
                    <div class="modal-body">
                        <div id="panel-edit-body"></div>
                    </div>
                    <div class="modal-footer">
                        <a href="#" id="btnPanelUpdate" class="btn btn-success pull-left">Update</a>
                        <a href="#" data-dismiss="modal" class="btn btn-primary pull-left">Exit</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CaseReviewApp/Views/ReviewPanel/_EditModalBody.cshtml
@model CaseReviewApp.Models.ReviewPanel
<form id="panel-form-edit">
    <div class="row">
        <div class="col-md-6">
            <h4>Case Title</h4>
        </div>
        <div class="col-md-6">
            <h4>Panel Members</h4>
        </div>
    </div>

    <input type="hidden" class="editHiddenCaseId" value="@Model.CaseID" />
    <input type="hidden" id="editHiddenReviewId" value="@Model.ReviewID" />
    <div class="row" id="edit_check_@Model.CaseID">
        <div class="col-md-6">
            <div class="checkbox">
                <label><input type="checkbox" checked disabled id="edit_case_@Model.CaseID" />@Model.Case.CaseTitle</label>
            </div>
        </div>
        <div class="col-md-6 member">
            @foreach (var member in ViewBag.AllMembers)
            {
                <div class="checkbox">
                    <label><input type="checkbox" @(Model.Members.AsEnumerable().Select(r => r.MemberID).ToList().Contains(member.MemberID) ? "checked" : "") id="@(String.Format("edit_case_{0}_{1}", Model.CaseID, member.MemberID))" />@member.Name</label>
                </div>
            }
        </div>
    </div>

    <span class="case-list-msg-edit error"></span>

    <div class="form-group">
        <label for="ReviewDetails">Review Details</label>
        <input type="text" value="@Model.ReviewDetails" required class="form-control" name="ReviewDetails" placeholder="Some details about the review">
    </div>
    <div class="form-group">
        <label for="CreatedBy">Created By</label>
        <input type="text" value="@Model.CreatedBy" required class="form-control" name="CreatedBy" placeholder="Name of the creator">
    </div>
    <div class="form-group">
        <label for="CreatedOn">Created On</label>
        <input type="text" required class="form-control" name="CreatedOn" value="@Model.CreatedOn" placeholder="Creation time">
    </div>
</form>

CaseReviewApp/Views/ReviewPanel/_ReviewDetails.cshtml
@model IEnumerable<CaseReviewApp.Models.ViewModels.ReviewPanelViewModel>
@if (!Model.Any())
{
    <h3 class="text-warning">No review panel is created yet</h3>
}
else
{
    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CaseTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReviewDetails)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Members)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CaseTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReviewDetails)
                </td>
                <td>
                    <ul>
                        @foreach (var member in item.Members)
                        {
                            <li>@Html.DisplayFor(modelItem => member.Name)</li>
                        }
                    </ul>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedOn)
                </td>
                <td><a href="javascript::return false;" class="btn btn-success" onclick="ShowEditModal(@item.ReviewID)"><i class="glyphicon glyphicon-pencil"></i> </a></td>
                <td><a href="javascript::return false;" class="btn btn-danger" onclick="ShowDelModal(@item.ReviewID)"><i class="glyphicon glyphicon-trash"></i> </a></td>
            </tr>
        }

    </table>
}

CaseReviewApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Case Review Panel Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .error {
            color: red;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Case Review Panel", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Member", "Index", "Member")</li>
                    <li>@Html.ActionLink("Cases", "Index", "Case")</li>
                    <li>@Html.ActionLink("Review Panel", "Index", "ReviewPanel")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/js/caseReview.js"></script>
</body>
</html>